version: '3'

services:
  html2pdf:
    build: .
    image: html2pdf
    ports:
    - "3000:8080"
    restart: always
    container_name: html2pdf
    networks:
    - custom_network

networks:
  custom_network:
    external:
      name: local_network